spring.application.name=budgeting1

spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/

# Lê a sua GEMINI_API_KEY configurada nos runners/ambiente
spring.ai.openai.api-key=${GEMINI_API_KEY:}

# Modelo que responderá às chamadas
spring.ai.openai.chat.options.model=gemini-2.5-flash

logging.level.org.springframework.ai=DEBUG